#!/usr/bin/env sh

START_U=0.4
END_U=0.9
STEP_U=0.1
TASKSET_NUMBER=1
TASKSET_FOLDER=taskset_auto_generated
SERVER_FOUND="The periodic server has the following paramters:"
BUDGET="	 Qs = "
PERIOD="	 Ts = "

is_contained() {
	./bin/find_ps_analysis $1 $2 | grep -q "$3"
}

get_value() {
	./bin/find_ps_analysis $1 $2 | grep "$3"
}


for U in $(seq $START_U $STEP_U $END_U); do
	printf "%s" "$U" >> tmp.txt
	for I in $(seq 0 3); do	
		B=0
		FOUND=0
		for T in $(seq 0 9); do
			./taskgen 5 $U $TASKSET_NUMBER
		
			if $(is_contained $TASKSET_FOLDER/ts_$TASKSET_NUMBER.txt $I "$SERVER_FOUND"); then
				Q_RESULT=$(get_value $TASKSET_FOLDER/ts_$TASKSET_NUMBER.txt $I "$BUDGET")
				T_RESULT=$(get_value $TASKSET_FOLDER/ts_$TASKSET_NUMBER.txt $I "$PERIOD")
				Q=${Q_RESULT#"$BUDGET"}
		  		T=${T_RESULT#"$PERIOD"}
		  		B=$(echo "scale=4;$B+$Q/$T" | bc)
		  		FOUND=$(($FOUND + 1))
			fi
			TASKSET_NUMBER=$(($TASKSET_NUMBER + 1))
		done
		
		if [ $FOUND != 0 ]; then
			B=$(echo "scale=4;$B/$FOUND" | bc)
		else
			B=0
		fi
		printf "\t%s" "$B" >> tmp.txt
	done 
	printf "\n" >> tmp.txt
done
