#!/usr/bin/env sh

START_U=0.4
END_U=0.9
STEP_U=0.1

START_S=0
END_S=3
STEP_S=1

START_U=0.4
END_U=0.9
STEP_U=0.1

TASKSET_NUMBER=1
TASKSET_FOLDER=taskset_auto_generated
SERVER_FOUND="The periodic server has the following paramters:"
BUDGET="	 Qs = "
PERIOD="	 Ts = "
FILENAME="test_h.txt"

task_generator() {
	./taskgen 5 $1 $2
}

is_contained() {
	./bin/find_ps_analysis $1 $2 | grep -q "$3"
}

get_value() {
	./bin/find_ps_analysis $1 $2 | grep "$3"
}

float_operation() {
	echo "scale=2; $1" | bc
}

for U in $(seq $START_U $STEP_U $END_U); do
	printf "%s" "$U" >> $FILENAME
	for S in $(seq $START_S $STEP_S $END_S); do	
		B=0
		FOUND=0
		for T in $(seq 0 9); do
			task_generator $U $TASKSET_NUMBER
		
			if $(is_contained $TASKSET_FOLDER/ts_$TASKSET_NUMBER.txt $S "$SERVER_FOUND"); then
				Q_RESULT=$(get_value $TASKSET_FOLDER/ts_$TASKSET_NUMBER.txt $S "$BUDGET")
				T_RESULT=$(get_value $TASKSET_FOLDER/ts_$TASKSET_NUMBER.txt $S "$PERIOD")
				Q=${Q_RESULT#"$BUDGET"}
		  		T=${T_RESULT#"$PERIOD"}
		  		B=$(float_operation "$B+$Q/$T")
		  		FOUND=$(($FOUND + 1))
			fi
			TASKSET_NUMBER=$(($TASKSET_NUMBER + 1))
		done
		
		if [ $FOUND != 0 ]; then
			B=$(float_operation "$B/$FOUND")
		else
			B=0
		fi
		printf "\t%s" "$B" >> $FILENAME
	done 
	printf "\n" >> $FILENAME
done
